---
tasks:
  - init: >
      pyenv install 3.10.4 &&
      pyenv global 3.10.4 &&
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    command: python --version
