---
image: gitpod/workspace-python-3.10:latest

github:
  prebuilds:
    addBadge: true

tasks:
  - name: Install dependencies
    before: |
      curl -sSL https://install.python-poetry.org | POETRY_HOME="${HOME}/.poetry" python3 - --yes --force
    command: poetry install
